// core/parts/control.ts

import type { MMPart } from "./types";

export const CONTROL_PARTS: MMPart[] = [
  {
    id: "mm-ctl-flight-f7",
    name: "AstraCore F7 Flight Controller",
    code: "CTL-FC-F7",
    category: "control",
    subtype: "flight-controller",
    tier: "advanced",
    massKg: 0.015,
    sizeM: { x: 0.036, y: 0.036, z: 0.012 },
    maxTorqueNm: null,
    maxSpeedRpm: null,
    maxThrustN: null,
    voltageV: 5,
    maxCurrentA: 0.3,
    powerW: 1.5,
    rangeM: null,
    updateRateHz: 1000,
    dof: null,
    jointLimitsRad: null,
    compatibleRobots: ["drone"],
    description: "High-performance F7-class flight controller for advanced multirotor control.",
  },
  {
    id: "mm-ctl-humanoid-rt",
    name: "Humanoid Real-Time Control Unit",
    code: "CTL-HUM-RT",
    category: "control",
    subtype: "humanoid-controller",
    tier: "elite",
    massKg: 0.45,
    sizeM: { x: 0.16, y: 0.12, z: 0.04 },
    maxTorqueNm: null,
    maxSpeedRpm: null,
    maxThrustN: null,
    voltageV: 24,
    maxCurrentA: 3,
    powerW: 72,
    rangeM: null,
    updateRateHz: 1000,
    dof: null,
    jointLimitsRad: null,
    compatibleRobots: ["humanoid"],
    description: "Real-time controller optimized for whole-body humanoid control and balance.",
  },
];
