// core/parts/sensors.ts

import type { MMPart } from "./types";

export const SENSOR_PARTS: MMPart[] = [
  {
    id: "mm-sns-imu-9dof",
    name: "InertialSense 9-DoF IMU",
    code: "SNS-IMU-9DOF",
    category: "sensor",
    subtype: "imu",
    tier: "standard",
    massKg: 0.008,
    sizeM: { x: 0.02, y: 0.02, z: 0.01 },
    maxTorqueNm: null,
    maxSpeedRpm: null,
    maxThrustN: null,
    voltageV: 5,
    maxCurrentA: 0.05,
    powerW: 0.25,
    rangeM: null,
    updateRateHz: 500,
    dof: null,
    jointLimitsRad: null,
    compatibleRobots: ["generic", "drone", "humanoid", "rover", "manipulator"],
    description: "9-axis IMU providing accelerometer, gyroscope, and magnetometer data.",
  },
  {
    id: "mm-sns-lidar-2d-lite",
    name: "ScanLite 2D Lidar",
    code: "SNS-LIDAR-2D-L",
    category: "sensor",
    subtype: "lidar-2d",
    tier: "standard",
    massKg: 0.18,
    sizeM: { x: 0.06, y: 0.06, z: 0.08 },
    maxTorqueNm: null,
    maxSpeedRpm: null,
    maxThrustN: null,
    voltageV: 12,
    maxCurrentA: 0.5,
    powerW: 6,
    rangeM: 12,
    updateRateHz: 10,
    dof: null,
    jointLimitsRad: null,
    compatibleRobots: ["rover", "generic", "humanoid"],
    description: "Short-range 2D lidar suitable for mapping and obstacle detection.",
  },
];
